motor_info:
        min_pwm: 0.59 # 1180 [ms]
        max_pwm: 0.9375 # 1875 [ms]
        min_thrust: 1.0 #  [N]
        force_landing_thrust: 6.5 #[N]
        m_f_rate: -0.0172
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 4
        ref1:
                voltage: 25.2
                max_thrust: 20 # N 
                polynominal2: 0.07983707 # x10
                polynominal1: -6.627443098 # x10
                polynominal0: 12.3593793002 # x1
        ref2:
                voltage: 24.2
                max_thrust: 19 # N 
                polynominal2: 0.078085358 # x10
                polynominal1: -6.641338225 # x10
                polynominal0: 12.9797798522 # x1
        ref3:
                voltage: 23.2
                max_thrust: 18 # N 
                polynominal2: 0.074527175 # x10
                polynominal1: -6.440853637 # x10
                polynominal0: 12.9565178437 # x1
        ref4:
                voltage: 22.2
                max_thrust: 16.8 # N 
                polynominal2: 0.071758366 # x10
                polynominal1: -6.346135548 # x10
                polynominal0: 13.2669467083 # x1

        # for simualtion
        rotor_damping_rate: 0.1
        rotor_force_noise: 0
        dual_rotor_moment_noise: 0
